version: 2
jobs:
  go-version-latest:
    docker:
      - image: cimg/go:1.17-node
    steps:
      - checkout
      - run: make
      - run: make alltest
  go-version-last:
    docker:
      - image: cimg/go:1.16-node
    steps:
      - checkout
      - run: make
      - run: make alltest

workflows:
  version: 2
  build_and_test:
    jobs:
      - go-version-latest
      - go-version-last
